---
description: TypeScript3.6のリリース内容まとめ
---

# [TypeScript] 3.6

{{ page.meta.description }}


## [Stricter Generators]

[Stricter Generators]: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-6.html#stricter-generators

{{label('should')}} {{label('normal')}}

ジェネレータ関数が`IterableIterator`ではなく`Generator`を返すようになった。  
それによってジェネレータの型判定が厳密になった。

### ジェネレータの返す値がyieldかreturnかを判別できるようになった

今までは`next(...)`の結果が以下どちらか判別できなかった。

* `yield`によって返された値
* `return`によって返された値

v3.6からは判別できるようになった。

#### 具体例

以下のコードは`r.done === true`の結果によって`it.next().value`の返却型は絞りこめる。

```typescript
function* countDown() {
  yield 3;
  yield 2;
  yield 1;
  return "Go";
}

const it = countDown();
while (true) {
  const r = it.next();
  if (r.done) {
    console.log(r.value);
    break;
  } else {
    console.log(r.value);
  }
}
```

TypeScript3.5では`r.done`の結果は考慮されないが、TypeScript3.6からは考慮して推論される。

=== "v3.5"
    ```typescript
    const it = countDown();
    while (true) {
      const r = it.next();
      if (r.done) {
          // r.valueは "Go" | 3 | 2 | 1 と推論される
        console.log(r.value);
        break;
      } else {
          // r.valueは "Go" | 3 | 2 | 1 と推論される
        console.log(r.value);
      }
    }
    ```

=== "v3.6"
    ```typescript
    const it = countDown();
    while (true) {
      const r = it.next();
      if (r.done) {
          // r.valueは string と推論される
        console.log(r.value);
        break;
      } else {
          // r.valueは 3 | 2 | 1 と推論される
        console.log(r.value);
      }
    }
    ```

#### 詳細

v3.6では`next(...)`が`IteratorResult`を返すようになった。  
これはyieldまたはreturnの返却値を意味する。

```typescript
type IteratorResult<T, TReturn = any> =
  | IteratorYieldResult<T>
  | IteratorReturnResult<TReturn>;

interface IteratorYieldResult<TYield> {
  done?: false;
  value: TYield;
}

interface IteratorReturnResult<TReturn> {
  done: true;
  value: TReturn;
}
```

`IteratorResult`は[Tagged union types]を使っているため、`next(...).done`の結果によって`next(...).value`の型が判別できる。


### yieldの戻り値型を考慮できるようになった (anyではなくなった)

v3.6では`.next(...)`の引数に適さない型を入れると、ちゃんとエラーになる。  
v3.5ではすべての型を受けつけていた。

#### 具体例

以下は`next`で渡した引数を繋げて出力していくコード。  
出力は`say saytake saytakehundred`となる。

```typescript
function* stringPrinter() {
  let result = "";
  while (true) {
    const received: string = yield result;
    result += received.toLowerCase();
  }
}

const it = stringPrinter();
console.log(
  it.next().value,
  it.next("Say").value,
  it.next("TAKE").value,
  it.next("hundred").value
);
```

最後の`next`に数値を入れてみる。  
v3.5ではエラーにならないが、`number`に`toLowerCase`はないため実行時に失敗する。

```typescript
function* stringPrinter() {
  let result = "";
  while (true) {
    const received: string = yield result;
    result += received.toLowerCase();
  }
}

const it = stringPrinter();
console.log(
  it.next().value,
  it.next("Say").value,
  it.next("TAKE").value,
  // Uncaught TypeError: received.toLowerCase is not a function
  it.next(100).value
);
```

#### 詳細

v3.5で実行前エラーにならないのは`next`の引数がanyになっているため。

```typescript
interface Iterator<T> {
    next(value?: any): IteratorResult<T>;
    return?(value?: any): IteratorResult<T>;
    throw?(e?: any): IteratorResult<T>;
}
```

v3.6ではGenerator型に対応しており、`next`が返す`TNext`の型と比較できるようになった。

```typescript
interface Generator<T = unknown, TReturn = any, TNext = unknown> extends Iterator<T, TReturn, TNext> {
    // NOTE: 'next' is defined using a tuple to ensure we report the correct assignability errors in all places.
    next(...args: [] | [TNext]): IteratorResult<T, TReturn>;
    return(value: TReturn): IteratorResult<T, TReturn>;
    throw(e: any): IteratorResult<T, TReturn>;
    [Symbol.iterator](): Generator<T, TReturn, TNext>;
}
```

これによって型エラーが検知される。

```
型 '100' を型 'string' に割り当てることはできません。ts(2345)
```


## [More Accurate Array Spread]

[More Accurate Array Spread]: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-6.html#more-accurate-array-spread

{{label('not_necessary')}} {{label('normal')}}

ArrayのSpreadがより正確になった。

`[...Array(5)]`は`[undefined, undefined, undefined, undefined, undefined]`を期待するが、`--downlevelIteration`なしだとv3.5では`Array(5).slice()`にトランスパイルされていた。

| TypeScriptバージョン | `--downlevelIteration` | `[...Array(5)]` のトランスパイル結果 |
| -------------------- | ---------------------- | ------------------------------------ |
| 3.5                  | true                   | `__spread(Array(5))`                 |
| 3.5                  | false                  | `Array(5).slice()`                   |
| 3.6                  | true                   | `__spread(Array(5))`                 |
| 3.6                  | false                  | `__spreadArrays(Array(5))`           |

v3.6からは`[undefined, undefined, undefined, undefined, undefined]`を返すようになる。


## [Improved UX Around Promises]

[Improved UX Around Promises]: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-6.html#improved-ux-around-promises

{{label('not_necessary')}} {{label('easy')}}

Promiseに関するエラーが分かりやすくなった。

```typescript
declare function createNumberPromise(): Promise<number>;
declare function showNumber(value: number): void;

async function f() {
  showNumber(createNumberPromise());
}
```

上記はPromiseを解決せず関数の引数に渡してしまった例。  
v3.5は真実のみを伝えているが、v3.6では`await`忘れではないかと提案してくれる。

=== "v3.5"
    ```
    index.ts:5:14 - error TS2345: Argument of type 'Promise<number>' is not assignable to parameter of type 'number'.

    5   showNumber(createNumberPromise());
    ```

=== "v3.6"
    ```
    index.ts:5:14 - error TS2345: Argument of type 'Promise<number>' is not assignable to parameter of type 'number'.

    5   showNumber(createNumberPromise());
    ~~~~~~~~~~~~~~~~~~~~~

    index.ts:5:14
    5   showNumber(createNumberPromise());
    ~~~~~~~~~~~~~~~~~~~~~
    Did you forget to use 'await'?
    ```

`Promise<T>`をawaitしないまま`T`に存在するプロパティを呼び出したときも同様の提案をしてくれる。  
...がこれはv3.5の時点から対応されていた。(リリースノートの間違い?)


## [Better Unicode Support for Identifiers]

[Better Unicode Support for Identifiers]: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-6.html#better-unicode-support-for-identifiers

{{label('not_necessary')}} {{label('easy')}}

targetに`es2015`以降を指定すると、Unicodeがよりサポートされるようになった。


## [import.meta Support in SystemJS]

[import.meta Support in SystemJS]: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-6.html#importmeta-support-in-systemjs

{{label('unknown')}} {{label('easy')}}

`module`ターゲットが`system`のとき`import.meta`を`context.meta`に変換するようになった。

!!! question "何が嬉しいかがわからない.."
    


[Tagged union types]: ../2.0/#tagged-union-types
